Нужно больше функций
htmlacademy-javascript/122895-kekstagram-28 pull request #2
Opened 2023-02-21 12:00 UTC by knosal

Решение задач 1-4

---
:mortar_board: [Нужно больше функций](https://up.htmlacademy.ru/javascript/28/user/122895/tasks/7)

2023-02-21 12:02 UTC, knosal commented
Возникли сложности с пониманием в 4 задачи, на словах вроде ясно что нужно сделать, но вот реализация.

2023-02-21 13:29 UTC, pavel-nyukalo requested changes

2023-02-21 13:29 UTC, pavel-nyukalo commented on index.html
> +<script src="/js/functions.js"></script>
На опубликованной версии не будет работать, поскольку там чуть другой `base`, отличный от локальной папки

Поэтому нужно сделать либо `./js/functions.js`, либо просто `js/functions.js`

2023-02-21 13:29 UTC, pavel-nyukalo commented on js/functions.js
> +const checkingLengthstring = (checkedString, evaluationСriteria) => checkedString.length <= evaluationСriteria ? 'true - строка проходит по длине' : 'false — строка не проходит';
Тут немного непонятки идут с ТЗ, Академия это признала.

Но наставник на то и есть, чтобы в нужное русло направлять 😁

В общем, нам тут нужно чтобы функция возвращала `true/false`. Именно булево значение, не строку.

В дальнейшем нам эта функция может понадобиться при валидации формы и там как раз нам нужны будут `true` или `false`

В таком случае все можно свести к одной строке
```js
const checkingLengthstring = (checkedString, evaluationСriteria) => checkedString.length <= evaluationСriteria
```

2023-02-21 13:29 UTC, pavel-nyukalo commented on js/functions.js
> +};
Аналогично, здесь надо будет возвращать просто true/false. То есть результат проверки `return withoutSpaces === reversePalidrome`

2023-02-21 13:29 UTC, pavel-nyukalo commented on js/functions.js
> +  return (isNaN(stringName)) ? 'Результат: NaN' : `Результат: число ${stringName}`;
Тут тоже, нужно возвращать именно `NaN`, или число. Не строки. Тут немного непонятки с тз идут, согласен. Но видишь тут как результат именно числа представлены

![image](https://user-images.githubusercontent.com/52506235/220357435-b88b8293-dcd4-4f7d-8142-11a91d98b1ee.png)

2023-02-21 13:29 UTC, pavel-nyukalo commented on js/functions.js
> +  return `Результат: строка ${sourceString}`;
А здесь просто нужно возвращать эту строку. Но то что ты попробовал шаблонные строки - круто!

2023-02-22 07:08 UTC, pavel-nyukalo approved these changes

2023-02-22 07:08 UTC, merged