4.16. Больше деталей
htmlacademy-javascript/122895-kekstagram-28 pull request #3
Opened 2023-02-28 09:15 UTC by knosal

1. Нужно ли сохранять состояние id в переменную, чтобы в значении ключа id, url были одинаковые данные?
2. Не ясно, почему создается 11 объектов, а дальше пишет перебран весь диапазон, как так, если 25 всего. В функции createRandomIdFromRangeGenerator.
3. --Описание фотографии для комментария пока не вставлял, просто копипаст из сообщений.
4.  Можно как-то упросить или сделать читабельнее getGeneraRandomlId, а то изобилие Math пугает?

2023-03-01 17:13 UTC, pavel-nyukalo requested changes

2023-03-01 17:13 UTC, pavel-nyukalo commented on js/main.js
> +const namesForComments = [
У нас это неизменяемые по сути константы, поэтому я бы предложил записать их в `UPPER_CASE`

2023-03-01 17:13 UTC, pavel-nyukalo commented on js/main.js
> +const generateAvatars = createRandomIdFromRangeGenerator(1, 6);
Так же у нас есть критерий на магические числа, и вот это все (1, 25, 15, 200, 1, 6) считается магическими - для них нужны константы в `UPPER_CASE`

2023-03-01 17:13 UTC, pavel-nyukalo commented on js/main.js
> +  const PhotoId = generatePhotosId();
Эту переменную нужно записать в `camelCase`, сейчас она записана в `PascalCase`

2023-03-01 17:13 UTC, pavel-nyukalo commented on js/main.js
> +    url: concatenatePathIdExtension('photos/', PhotoId, '.jpg'),
Я бы предложил тут делать шаблонные строки, вместо вызова функции

1. У тебя уйдет лишняя функция
2. Есть критерий, который говорит чтобы мы использовали шаблонные строки вместо конкатенации

И тут будет

```js
url: `photos/${ photoId }.jpg`,
```

2023-03-01 17:13 UTC, pavel-nyukalo commented on js/main.js
> +      avatar: concatenatePathIdExtension('img/avatar-', generateAvatars(), '.svg'),
Тут аналогично про шаблоные строки

2023-03-01 17:13 UTC, pavel-nyukalo commented on js/main.js
> +//const similarPhotos = Array.from({ length: PHOTOS_OBJECTS_COUNT }, createPublishedPhoto);
В целом все работает корректно, ситуации где бы создались 11 не нашел

Единственное, вот тут немного надо пошаманить с условием в генерации `id`

![image](https://user-images.githubusercontent.com/52506235/222212485-d9fa3ebe-deed-4640-ba1d-24a8f8842738.png)

2023-03-02 18:00 UTC, knosal commented on js/main.js
> +    url: concatenatePathIdExtension('photos/', PhotoId, '.jpg'),
биктики использовать, понял.

2023-03-02 18:55 UTC, knosal commented on js/main.js
> +//const similarPhotos = Array.from({ length: PHOTOS_OBJECTS_COUNT }, createPublishedPhoto);
1. Не понимаю почему теряется одно значение id, бывает число 5, бывает 7 и .т.д. 
2. И что должно выдавать id, когда все значения из диапазона выставлены?

2023-03-05 10:17 UTC, pavel-nyukalo approved these changes

2023-03-05 10:17 UTC, merged